defmodule TodoDesktopappWeb.Endpoint do
  # use Phoenix.Endpoint, otp_app: :todo_desktopapp
  # Step 1: Change the endpoint as a `Desktop` endpoint.
  use Desktop.Endpoint, otp_app: :todo_desktopapp

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_todo_desktopapp_key",
    signing_salt: "atgcHrQm",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :todo_desktopapp,
    gzip: not code_reloading?,
    only: TodoDesktopappWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :todo_desktopapp
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Step 2: Add `Desktop.Auth` plug to ensure that only requests from
  # the Desktop app's WebView are allowed.
  plug Desktop.Auth
  plug TodoDesktopappWeb.Router
end
