import Config

config :todo_desktopapp, :environment, :prod

# Configure your database
config :todo_desktopapp, TodoDesktopapp.Repo,
  database:
    Path.join([
      System.user_home(),
      ".config",
      "todo_desktopapp",
      "database.sqlite3"
    ]),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :todo_desktopapp, TodoDesktopappWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: :crypto.strong_rand_bytes(64)

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
